/*
 * Seabattle API
 * Сервис для игры в морской бой
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nirku0soft@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.fizlrock.seabattle.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BoatCordDto
 */
class BoatCordDtoTest {
    private final BoatCordDto model = new BoatCordDto();

    /**
     * Model tests for BoatCordDto
     */
    @Test
    void testBoatCordDto() {
        // TODO: test BoatCordDto
    }

    /**
     * Test the property 'xs'
     */
    @Test
    void xsTest() {
        // TODO: test xs
    }

    /**
     * Test the property 'ys'
     */
    @Test
    void ysTest() {
        // TODO: test ys
    }

    /**
     * Test the property 'xe'
     */
    @Test
    void xeTest() {
        // TODO: test xe
    }

    /**
     * Test the property 'ye'
     */
    @Test
    void yeTest() {
        // TODO: test ye
    }

}
