/*
 * Seabattle API
 * Сервис для игры в морской бой
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nirku0soft@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.fizlrock.seabattle.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GameStateDto
 */
class GameStateDtoTest {
    private final GameStateDto model = new GameStateDto();

    /**
     * Model tests for GameStateDto
     */
    @Test
    void testGameStateDto() {
        // TODO: test GameStateDto
    }

    /**
     * Test the property 'changeCount'
     */
    @Test
    void changeCountTest() {
        // TODO: test changeCount
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'oponentId'
     */
    @Test
    void oponentIdTest() {
        // TODO: test oponentId
    }

    /**
     * Test the property 'youShoting'
     */
    @Test
    void youShotingTest() {
        // TODO: test youShoting
    }

    /**
     * Test the property 'yourField'
     */
    @Test
    void yourFieldTest() {
        // TODO: test yourField
    }

    /**
     * Test the property 'oponentField'
     */
    @Test
    void oponentFieldTest() {
        // TODO: test oponentField
    }

}
