/*
 * Seabattle API
 * Сервис для игры в морской бой
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nirku0soft@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.fizlrock.seabattle.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GameStatsDto
 */
class GameStatsDtoTest {
    private final GameStatsDto model = new GameStatsDto();

    /**
     * Model tests for GameStatsDto
     */
    @Test
    void testGameStatsDto() {
        // TODO: test GameStatsDto
    }

    /**
     * Test the property 'number'
     */
    @Test
    void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'opponentName'
     */
    @Test
    void opponentNameTest() {
        // TODO: test opponentName
    }

    /**
     * Test the property 'hitPercentage'
     */
    @Test
    void hitPercentageTest() {
        // TODO: test hitPercentage
    }

    /**
     * Test the property 'duration'
     */
    @Test
    void durationTest() {
        // TODO: test duration
    }

}
