/*
 * Seabattle API
 * Сервис для игры в морской бой
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nirku0soft@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.fizlrock.seabattle.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.fizlrock.seabattle.model.BoatTypeDto;
import dev.fizlrock.seabattle.model.GameMapSettingsDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GameSettingsDto
 */
class GameSettingsDtoTest {
    private final GameSettingsDto model = new GameSettingsDto();

    /**
     * Model tests for GameSettingsDto
     */
    @Test
    void testGameSettingsDto() {
        // TODO: test GameSettingsDto
    }

    /**
     * Test the property 'boatTypesDto'
     */
    @Test
    void boatTypesDtoTest() {
        // TODO: test boatTypesDto
    }

    /**
     * Test the property 'gameMapSettingsDto'
     */
    @Test
    void gameMapSettingsDtoTest() {
        // TODO: test gameMapSettingsDto
    }

}
