/*
 * Seabattle API
 * Сервис для игры в морской бой
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nirku0soft@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.fizlrock.seabattle.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RegistrationRequestBody
 */
class RegistrationRequestBodyTest {
    private final RegistrationRequestBody model = new RegistrationRequestBody();

    /**
     * Model tests for RegistrationRequestBody
     */
    @Test
    void testRegistrationRequestBody() {
        // TODO: test RegistrationRequestBody
    }

    /**
     * Test the property 'login'
     */
    @Test
    void loginTest() {
        // TODO: test login
    }

    /**
     * Test the property 'password'
     */
    @Test
    void passwordTest() {
        // TODO: test password
    }

}
