/*
 * Seabattle API
 * Сервис для игры в морской бой
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nirku0soft@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.fizlrock.seabattle.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserProfileDto
 */
class UserProfileDtoTest {
    private final UserProfileDto model = new UserProfileDto();

    /**
     * Model tests for UserProfileDto
     */
    @Test
    void testUserProfileDto() {
        // TODO: test UserProfileDto
    }

    /**
     * Test the property 'avatarId'
     */
    @Test
    void avatarIdTest() {
        // TODO: test avatarId
    }

    /**
     * Test the property 'pictureUrl'
     */
    @Test
    void pictureUrlTest() {
        // TODO: test pictureUrl
    }

}
