/*
 * Seabattle API
 * Сервис для игры в морской бой
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nirku0soft@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.fizlrock.seabattle.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Описание расположения одного корабля на карте
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class BoatCordDto {
  public static final String SERIALIZED_NAME_XS = "xs";
  @SerializedName(SERIALIZED_NAME_XS)
  @javax.annotation.Nullable
  private Integer xs;

  public static final String SERIALIZED_NAME_YS = "ys";
  @SerializedName(SERIALIZED_NAME_YS)
  @javax.annotation.Nullable
  private Integer ys;

  public static final String SERIALIZED_NAME_XE = "xe";
  @SerializedName(SERIALIZED_NAME_XE)
  @javax.annotation.Nullable
  private Integer xe;

  public static final String SERIALIZED_NAME_YE = "ye";
  @SerializedName(SERIALIZED_NAME_YE)
  @javax.annotation.Nullable
  private Integer ye;

  public BoatCordDto() {
  }

  public BoatCordDto xs(@javax.annotation.Nullable Integer xs) {
    
    this.xs = xs;
    return this;
  }

  /**
   * Координата начала корабля по оси X
   * @return xs
   */
  @javax.annotation.Nullable

  public Integer getXs() {
    return xs;
  }


  public void setXs(@javax.annotation.Nullable Integer xs) {
    this.xs = xs;
  }

  public BoatCordDto ys(@javax.annotation.Nullable Integer ys) {
    
    this.ys = ys;
    return this;
  }

  /**
   * Координата начала корабля по оси Y
   * @return ys
   */
  @javax.annotation.Nullable

  public Integer getYs() {
    return ys;
  }


  public void setYs(@javax.annotation.Nullable Integer ys) {
    this.ys = ys;
  }

  public BoatCordDto xe(@javax.annotation.Nullable Integer xe) {
    
    this.xe = xe;
    return this;
  }

  /**
   * Координата конца корабля по оси X
   * @return xe
   */
  @javax.annotation.Nullable

  public Integer getXe() {
    return xe;
  }


  public void setXe(@javax.annotation.Nullable Integer xe) {
    this.xe = xe;
  }

  public BoatCordDto ye(@javax.annotation.Nullable Integer ye) {
    
    this.ye = ye;
    return this;
  }

  /**
   * Координата конца корабля по оси Y
   * @return ye
   */
  @javax.annotation.Nullable

  public Integer getYe() {
    return ye;
  }


  public void setYe(@javax.annotation.Nullable Integer ye) {
    this.ye = ye;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoatCordDto boatCordDto = (BoatCordDto) o;
    return Objects.equals(this.xs, boatCordDto.xs) &&
        Objects.equals(this.ys, boatCordDto.ys) &&
        Objects.equals(this.xe, boatCordDto.xe) &&
        Objects.equals(this.ye, boatCordDto.ye);
  }

  @Override
  public int hashCode() {
    return Objects.hash(xs, ys, xe, ye);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoatCordDto {\n");
    sb.append("    xs: ").append(toIndentedString(xs)).append("\n");
    sb.append("    ys: ").append(toIndentedString(ys)).append("\n");
    sb.append("    xe: ").append(toIndentedString(xe)).append("\n");
    sb.append("    ye: ").append(toIndentedString(ye)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private BoatCordDto instance;

    public Builder() {
      this(new BoatCordDto());
    }

    protected Builder(BoatCordDto instance) {
      this.instance = instance;
    }

    public BoatCordDto.Builder xs(Integer xs) {
      this.instance.xs = xs;
      return this;
    }
    public BoatCordDto.Builder ys(Integer ys) {
      this.instance.ys = ys;
      return this;
    }
    public BoatCordDto.Builder xe(Integer xe) {
      this.instance.xe = xe;
      return this;
    }
    public BoatCordDto.Builder ye(Integer ye) {
      this.instance.ye = ye;
      return this;
    }


    /**
    * returns a built BoatCordDto instance.
    *
    * The builder is not reusable.
    */
    public BoatCordDto build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static BoatCordDto.Builder builder() {
    return new BoatCordDto.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public BoatCordDto.Builder toBuilder() {
    return new BoatCordDto.Builder()
      .xs(getXs())
      .ys(getYs())
      .xe(getXe())
      .ye(getYe());
  }


}

