/*
 * Seabattle API
 * Сервис для игры в морской бой
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nirku0soft@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.fizlrock.seabattle.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * GameStatsDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class GameStatsDto {
  public static final String SERIALIZED_NAME_NUMBER = "number";
  @SerializedName(SERIALIZED_NAME_NUMBER)
  @javax.annotation.Nullable
  private Integer number;

  public static final String SERIALIZED_NAME_YOU_WIN = "you_win";
  @SerializedName(SERIALIZED_NAME_YOU_WIN)
  @javax.annotation.Nullable
  private Boolean youWin;

  public static final String SERIALIZED_NAME_OPPONENT_NAME = "opponent_name";
  @SerializedName(SERIALIZED_NAME_OPPONENT_NAME)
  @javax.annotation.Nullable
  private String opponentName;

  public static final String SERIALIZED_NAME_HIT_PERCENTAGE = "hit_percentage";
  @SerializedName(SERIALIZED_NAME_HIT_PERCENTAGE)
  @javax.annotation.Nullable
  private Integer hitPercentage;

  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  @javax.annotation.Nullable
  private Integer duration;

  public GameStatsDto() {
  }

  public GameStatsDto number(@javax.annotation.Nullable Integer number) {
    
    this.number = number;
    return this;
  }

  /**
   * Порядковый номер игры
   * minimum: 0
   * @return number
   */
  @javax.annotation.Nullable

  public Integer getNumber() {
    return number;
  }


  public void setNumber(@javax.annotation.Nullable Integer number) {
    this.number = number;
  }

  public GameStatsDto youWin(@javax.annotation.Nullable Boolean youWin) {
    
    this.youWin = youWin;
    return this;
  }

  /**
   * Get youWin
   * @return youWin
   */
  @javax.annotation.Nullable

  public Boolean getYouWin() {
    return youWin;
  }


  public void setYouWin(@javax.annotation.Nullable Boolean youWin) {
    this.youWin = youWin;
  }

  public GameStatsDto opponentName(@javax.annotation.Nullable String opponentName) {
    
    this.opponentName = opponentName;
    return this;
  }

  /**
   * Имя противника
   * @return opponentName
   */
  @javax.annotation.Nullable

  public String getOpponentName() {
    return opponentName;
  }


  public void setOpponentName(@javax.annotation.Nullable String opponentName) {
    this.opponentName = opponentName;
  }

  public GameStatsDto hitPercentage(@javax.annotation.Nullable Integer hitPercentage) {
    
    this.hitPercentage = hitPercentage;
    return this;
  }

  /**
   * Процент попаданий
   * minimum: 0
   * maximum: 100
   * @return hitPercentage
   */
  @javax.annotation.Nullable

  public Integer getHitPercentage() {
    return hitPercentage;
  }


  public void setHitPercentage(@javax.annotation.Nullable Integer hitPercentage) {
    this.hitPercentage = hitPercentage;
  }

  public GameStatsDto duration(@javax.annotation.Nullable Integer duration) {
    
    this.duration = duration;
    return this;
  }

  /**
   * Длительность поединка в миллисекундах
   * minimum: 0
   * @return duration
   */
  @javax.annotation.Nullable

  public Integer getDuration() {
    return duration;
  }


  public void setDuration(@javax.annotation.Nullable Integer duration) {
    this.duration = duration;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameStatsDto gameStatsDto = (GameStatsDto) o;
    return Objects.equals(this.number, gameStatsDto.number) &&
        Objects.equals(this.youWin, gameStatsDto.youWin) &&
        Objects.equals(this.opponentName, gameStatsDto.opponentName) &&
        Objects.equals(this.hitPercentage, gameStatsDto.hitPercentage) &&
        Objects.equals(this.duration, gameStatsDto.duration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, youWin, opponentName, hitPercentage, duration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameStatsDto {\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    youWin: ").append(toIndentedString(youWin)).append("\n");
    sb.append("    opponentName: ").append(toIndentedString(opponentName)).append("\n");
    sb.append("    hitPercentage: ").append(toIndentedString(hitPercentage)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private GameStatsDto instance;

    public Builder() {
      this(new GameStatsDto());
    }

    protected Builder(GameStatsDto instance) {
      this.instance = instance;
    }

    public GameStatsDto.Builder number(Integer number) {
      this.instance.number = number;
      return this;
    }
    public GameStatsDto.Builder youWin(Boolean youWin) {
      this.instance.youWin = youWin;
      return this;
    }
    public GameStatsDto.Builder opponentName(String opponentName) {
      this.instance.opponentName = opponentName;
      return this;
    }
    public GameStatsDto.Builder hitPercentage(Integer hitPercentage) {
      this.instance.hitPercentage = hitPercentage;
      return this;
    }
    public GameStatsDto.Builder duration(Integer duration) {
      this.instance.duration = duration;
      return this;
    }


    /**
    * returns a built GameStatsDto instance.
    *
    * The builder is not reusable.
    */
    public GameStatsDto build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static GameStatsDto.Builder builder() {
    return new GameStatsDto.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public GameStatsDto.Builder toBuilder() {
    return new GameStatsDto.Builder()
      .number(getNumber())
      .youWin(getYouWin())
      .opponentName(getOpponentName())
      .hitPercentage(getHitPercentage())
      .duration(getDuration());
  }


}

