/*
 * Seabattle API
 * Сервис для игры в морской бой
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nirku0soft@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.fizlrock.seabattle.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Стратегия расстановки кораблей 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PlacementStrategyDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public PlacementStrategyDto() {
  }

  public PlacementStrategyDto id(@javax.annotation.Nonnull Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 0
   * @return id
   */
  @javax.annotation.Nonnull

  public Long getId() {
    return id;
  }


  public void setId(@javax.annotation.Nonnull Long id) {
    this.id = id;
  }

  public PlacementStrategyDto name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlacementStrategyDto placementStrategyDto = (PlacementStrategyDto) o;
    return Objects.equals(this.id, placementStrategyDto.id) &&
        Objects.equals(this.name, placementStrategyDto.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlacementStrategyDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private PlacementStrategyDto instance;

    public Builder() {
      this(new PlacementStrategyDto());
    }

    protected Builder(PlacementStrategyDto instance) {
      this.instance = instance;
    }

    public PlacementStrategyDto.Builder id(Long id) {
      this.instance.id = id;
      return this;
    }
    public PlacementStrategyDto.Builder name(String name) {
      this.instance.name = name;
      return this;
    }


    /**
    * returns a built PlacementStrategyDto instance.
    *
    * The builder is not reusable.
    */
    public PlacementStrategyDto build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static PlacementStrategyDto.Builder builder() {
    return new PlacementStrategyDto.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public PlacementStrategyDto.Builder toBuilder() {
    return new PlacementStrategyDto.Builder()
      .id(getId())
      .name(getName());
  }


}

