/*
 * Seabattle API
 * Сервис для игры в морской бой
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nirku0soft@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.fizlrock.seabattle.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * ShotDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ShotDto {
  public static final String SERIALIZED_NAME_X = "x";
  @SerializedName(SERIALIZED_NAME_X)
  @javax.annotation.Nonnull
  private Integer x;

  public static final String SERIALIZED_NAME_Y = "y";
  @SerializedName(SERIALIZED_NAME_Y)
  @javax.annotation.Nonnull
  private Integer y;

  public ShotDto() {
  }

  public ShotDto x(@javax.annotation.Nonnull Integer x) {
    
    this.x = x;
    return this;
  }

  /**
   * Get x
   * @return x
   */
  @javax.annotation.Nonnull

  public Integer getX() {
    return x;
  }


  public void setX(@javax.annotation.Nonnull Integer x) {
    this.x = x;
  }

  public ShotDto y(@javax.annotation.Nonnull Integer y) {
    
    this.y = y;
    return this;
  }

  /**
   * Get y
   * @return y
   */
  @javax.annotation.Nonnull

  public Integer getY() {
    return y;
  }


  public void setY(@javax.annotation.Nonnull Integer y) {
    this.y = y;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShotDto shotDto = (ShotDto) o;
    return Objects.equals(this.x, shotDto.x) &&
        Objects.equals(this.y, shotDto.y);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x, y);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShotDto {\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ShotDto instance;

    public Builder() {
      this(new ShotDto());
    }

    protected Builder(ShotDto instance) {
      this.instance = instance;
    }

    public ShotDto.Builder x(Integer x) {
      this.instance.x = x;
      return this;
    }
    public ShotDto.Builder y(Integer y) {
      this.instance.y = y;
      return this;
    }


    /**
    * returns a built ShotDto instance.
    *
    * The builder is not reusable.
    */
    public ShotDto build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ShotDto.Builder builder() {
    return new ShotDto.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ShotDto.Builder toBuilder() {
    return new ShotDto.Builder()
      .x(getX())
      .y(getY());
  }


}

